const pacientes = [
  {
    id: "01",
    propietario: "Franco Rossi",
    nombre: "Moshi",
    especie: "Gato",
    sexo: "Macho",
    telefono: "099999",
    socio: "true",
    fechaNacimiento: "12/12/2015",
    castrado: "false",
    vacunado: "true",
    fechaVacunado: "12/12/1990",
    desparasitado: "true",
    fechaDesparasitado: "12/12/1990",
    antipulgas: "true",
    fechaAntipulgas: "12/12/1990",
  },
  {
    id: "02",
    propietario: "Dayana Meneses",
    nombre: "India",
    especie: "Gato",
    sexo: "Hembra",
    telefono: "099999",
    socio: "true",
    fechaNacimiento: "12/12/2015",
    castrado: "false",
    vacunado: "true",
    fechaVacunado: "12/12/1990",
    desparasitado: "true",
    fechaDesparasitado: "12/12/1990",
    antipulgas: "true",
    fechaAntipulgas: "12/12/1990",
  },
  {
    id: "03",
    propietario: "Franco Rossi",
    nombre: "Moshi",
    especie: "Gato",
    sexo: "Macho",
  },
  {
    id: "04",
    propietario: "Dayana Meneses",
    nombre: "India",
    especie: "Gato",
    sexo: "Hembra",
  },
  {
    id: "05",
    propietario: "Franco Rossi",
    nombre: "Moshi",
    especie: "Gato",
    sexo: "Macho",
  },
  {
    id: "06",
    propietario: "Dayana Meneses",
    nombre: "India",
    especie: "Gato",
    sexo: "Hembra",
  },
  {
    id: "07",
    propietario: "Franco Rossi",
    nombre: "Moshi",
    especie: "Gato",
    sexo: "Macho",
  },
  {
    id: "08",
    propietario: "Dayana Meneses",
    nombre: "India",
    especie: "Gato",
    sexo: "Hembra",
  },
  {
    id: "09",
    propietario: "Franco Rossi",
    nombre: "Moshi",
    especie: "Gato",
    sexo: "Macho",
  },
  {
    id: "10",
    propietario: "Dayana Meneses",
    nombre: "India",
    especie: "Gato",
    sexo: "Hembra",
  },
];
export default pacientes;
